name: Build Stuff

on:
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./build.sh
