name: Deploy to Sandbox

on:
  repository_dispatch:
    types: deploy-sandbox

  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA'
        required: true

jobs:
  deploy-to-sandbox:
    if: ${{ github.event.client_payload != null || github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to Sandbox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha || env.GITHUB_SHA }}

      - name: Deploy
        env:
          COMMIT_SHA: ${{ github.event.client_payload.sha }}
          EVENT_DATA: ${{ github.event.inputs.commit_sha }}
        run: |
          echo "Deploying commit $COMMIT_SHA to sandbox environment"
          echo "Commit SHA from event: $EVENT_DATA"
          ./deploy.sh $COMMIT_SHA sandbox.foo.bar
