name: Deploy to Prod

on:
  repository_dispatch:
    types: deploy-prod

jobs:
  deploy-to-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Deploy
        env:
          COMMIT_SHA: ${{ github.event.client_payload.sha }}
        run: |
          echo "Deploying commit $COMMIT_SHA to prod environment"
          ./deploy.sh $COMMIT_SHA prod.foo.bar
