name: Deploy to Prod

on:
  repository_dispatch:
    types: deploy-prod

jobs:
  deploy-to-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Deploy
        env:
          COMMIT_SHA: ${{ github.event.client_payload.sha }}
        run: |
          echo "Deploying commit $COMMIT_SHA to prod environment"
          ./deploy.sh $COMMIT_SHA prod.foo.bar

      - name: Workflow Dispatch
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          INPUT_DATA='{"ref": "master", "inputs": {"commit_sha": "$COMMIT_SHA"}}'
          echo "Invoking workflow dispatch"
          curl -XPOST \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'Authorization: Bearer $DEPLOY_TOKEN'
            https://api.github.com/repos/ygunayer/actions-test/workflows/deploy-sandbox/dispatches \
            -d $INPUT_DATA
