name: Deploy to Sandbox

on:
  repository_dispatch:
    types: deploy-sandbox

  workflow_run:
    workflows: ["Deploy to Prod"]
    branches: [master]
    types:
      - completed

jobs:
  deploy-to-sandbox:
    if: ${{ github.event.client_payload != null || github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to Sandbox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha || env.GITHUB_SHA }}

      - name: Deploy
        env:
          COMMIT_SHA: ${{ github.event.client_payload.sha }}
          REFS_URL: ${{ github.event.workflow_run.repository.git_refs_url }}
        run: |
          echo "Deploying commit $COMMIT_SHA to sandbox environment (REFS URL: $REFS_URL)"
          ./deploy.sh $COMMIT_SHA sandbox.foo.bar
